### PR TITLE
Linted

### PR DESCRIPTION
**Pull request by dherrada**

### CODE REVIEW

**Comment by dherrada** [comment]
@tannewt do I need to mock something for this? I don't think I've ever come across something that has failed in this specific way

**Comment by tannewt** [comment]
Looks like monotonic_ns was added in Python 3.7: https://docs.python.org/3/library/time.html#time.monotonic_ns We should probably switch everything to 3.7 or newer from 3.6.

**Comment by dherrada** [comment]
@tannewt Ok. I'll make a patch for that

**Review by tannewt — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
